Compile fixes for Qt6 on Windows
86Box/86Box pull request #4274
Opened 2024-03-15 19:47 UTC by Cacodemon345

Summary
=======
Qt6 on Windows defines the UNICODE macro by default unlike Qt5. This PR fixes compilation with Qt6 on Windows by forcing it and changing the WinBox manager checks to use Unicode strings.

Checklist
=========
* [ ] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
None.

2024-03-15 19:52 UTC, lemondrops commented
Don't we already define `UNICODE` in <86box/win.h>, which is included in qt_main.cpp?

2024-03-15 19:56 UTC, Cacodemon345 commented
It is defined, yes, but I think UNICODE needs to be defined to `1` instead of an empty value.

2024-03-15 20:08 UTC, cold-brewed commented
> It is defined, yes, but I think UNICODE needs to be defined to `1` instead of an empty value.

Have you verified that it is required to be like that?

2024-03-15 20:27 UTC, Cacodemon345 commented
Actually, I think it needs to be defined before including any headers. So including <86box/win.h> in the middle wouldn't work.

Also, on second thought, UNICODE can be defined to an empty value since that's how the Win32 UI did it.

2024-03-21 15:01 UTC, Biswa96 commented
I have brewed a different patch. It is not required to define `_UNICODE` macro explicitly. In the following patch, the string data type (char vs. wchar_t) is automatically set with `_T()` macro.

<details><summary>Click here to see the diff</summary>

```diff
--- a/src/qt/qt_main.cpp
+++ b/src/qt/qt_main.cpp
@@ -46,6 +46,7 @@
 #    include "qt_winmanagerfilter.hpp"
 #    include <86box/win.h>
 #    include <shobjidl.h>
+#    include <tchar.h>
 #endif
 
 extern "C" {
@@ -220,13 +221,13 @@
 
 #ifdef Q_OS_WINDOWS
 #    if !defined(EMU_BUILD_NUM) || (EMU_BUILD_NUM != 5624)
-    HWND winbox = FindWindow("TWinBoxMain", NULL);
+    HWND winbox = FindWindow(_T("TWinBoxMain"), NULL);
     if (winbox &&
-        FindWindowEx(winbox, NULL, "TToolBar", NULL) &&
-        FindWindowEx(winbox, NULL, "TListBox", NULL) &&
-        FindWindowEx(winbox, NULL, "TStatusBar", NULL) &&
-        (winbox = FindWindowEx(winbox, NULL, "TPageControl", NULL)) && /* holds a TTabSheet even on VM pages */
-        FindWindowEx(winbox, NULL, "TTabSheet", NULL))
+        FindWindowEx(winbox, NULL, _T("TToolBar"), NULL) &&
+        FindWindowEx(winbox, NULL, _T("TListBox"), NULL) &&
+        FindWindowEx(winbox, NULL, _T("TStatusBar"), NULL) &&
+        (winbox = FindWindowEx(winbox, NULL, _T("TPageControl"), NULL)) && /* holds a TTabSheet even on VM pages */
+        FindWindowEx(winbox, NULL, _T("TTabSheet"), NULL))
 #    endif
     {
         QMessageBox warningbox(QMessageBox::Icon::Warning, QObject::tr("WinBox is no longer supported"),
```

</details>

2024-03-21 15:06 UTC, Biswa96 commented
Little example about what it does.

* If `_UNICODE` is defined:
  - `FindWindow` becomes `FindWindowW`
  - `"TWinBoxMain"` becomes `L"TWinBoxMain"`
* If `_UNICODE` is not defined, no change.

2024-06-03 08:43 UTC, dhrdlicka requested changes

2024-06-03 08:43 UTC, dhrdlicka commented on src/qt/qt_main.cpp
> +#endif
No need, just don't use the tchar macros and call the function with the appropriate suffix explicitly if you're hardcoding narrow/wide strings

2024-06-03 08:43 UTC, dhrdlicka commented on src/qt/qt_main.cpp
> +        FindWindowEx(winbox, NULL, L"TTabSheet", NULL))
```suggestion
        FindWindowExW(winbox, NULL, L"TToolBar", NULL) &&
        FindWindowExW(winbox, NULL, L"TListBox", NULL) &&
        FindWindowExW(winbox, NULL, L"TStatusBar", NULL) &&
        (winbox = FindWindowExW(winbox, NULL, L"TPageControl", NULL)) && /* holds a TTabSheet even on VM pages */
        FindWindowExW(winbox, NULL, L"TTabSheet", NULL))
```

2024-06-16 12:36 UTC, merged